const AudioActionTypes = {
    TRIG_GAME_SOUND : 'TRIG_GAME_SOUND',
    START_THEME_MUSIC : 'START_THEME_MUSIC ',



    TRIG_SOUND : 'TRIG_SOUND',
    PLAY_ALL_SOUNDS : 'PLAY_ALL_SOUNDS',
    STOP_PLAYING_SOUND : 'STOP_PLAYING_SOUND',
    UPDATE_VOLUME : 'UPDATE_VOLUME',
    UPDATE_PITCH : 'UPDATE_PITCH',
    PLAY_GRAIN : 'PLAY_GRAIN',
}
export default AudioActionTypes